name: Auto Increment Tag

on:
  push:
    branches:
      - master   # 或 master，根据你的主分支修改

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch all tags
        run: git fetch --tags origin

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)
          echo "Latest tag: $TAG"
          if [ -z "$TAG" ]; then
            TAG="v0.0.0"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Bump tag
        id: bump_tag
        run: |
          IFS='.' read -r -a parts <<< "${TAG#v}"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}
          patch=$((patch+1))
          NEW_TAG="v$major.$minor.$patch"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "New tag: $NEW_TAG"

      - name: Create and push tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG
